spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

space-club:
  system:
    max-affordable-seconds: 3

---
spring:
  config:
    activate:
      on-profile: production
    import: secrets/application-production.yml

---
spring:
  config:
    activate:
      on-profile: develop
    import:
      - develop/application-develop.yml
      - application-global.yml
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - local/application-local.yml
      - application-global.yml
