spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
  jpa:
    open-in-view: false

s3:
  valid-extensions:
    - jpg
    - jpeg
    - png

space-club:
  system:
    max-affordable-seconds: 3

interceptor:
  token-prefix: "Bearer "

  path-to-exclude:
    - path: /api/v1/users
      method: POST

    - path: /api/v1/clubs/invites/
      method: GET

    - path: /api/v1/events
      method: GET

    - path: /api/v1/events/searches
      method: GET

    - path: /api/v1/users/oauth
      method: POST

    - path: /api/v1/events/banner
      method: GET

web:
  interceptor-path-pattern: /api/v1/**

bad-word:
  path: src/main/resources/secrets/bad_word_list.txt
