spring:
  datasource:
    url: ENC(KuDsTLkwQpRPgFytbh8BA54kBO37e6P9bCR1xlz2l8Ylf0NN38jH48ZoOB4HfVICvGPrX8nb0RhfhEeBhv7/bGg6MTak/kWms4VUqBXFT5kYb5fr0Tz9KLMqBfkI9hibGY2nzYZ0XU4=)
    username: ENC(4h2d2+xkCOzO1lh3R5J1Gw==)
    password: ENC(RiMn2xWrRb3iNOuRye4f8W+lCx+M/cjb)
    driver-class-name: com.mysql.cj.jdbc.Driver

s3:
  bucket:
    name: ENC(kSZb9yw2JDAVxz/12V7CRNzRskzFvwgqKzJdZzg2nWdIHAnbxBvfknN0fEBTL1j3C6t4LC1iqXk=)
  iam:
    access-key: ENC(1G8ZGZQKMoihcCiT2kgRMLqmKHWfk10LtbhDURaLzDs=)
    secret-key: ENC(iVBb5DDSSAGVQhCL6/KnOPKWC3x89s+9s9SyvR+7/55uBtkdhmL0aobUoL1uGa+67NYXjP1KRUI=)
    region: ENC(906H8BMOAumiA+H0nevzxJUoUGzBG2Nh)
