spring:
  datasource:
    url: ENC(otDA9awhWaUEIpsnbNeFYbtGftRKQJGT0sJCi+wsST/vLIAY7qgtfWUJ5DboDjtm75FCMg9NpMIO51aQRFjS9cjjelWOUltFnMEd2c295NvXg8xVH7Xm3eoDuXuSjWRH)
    username: ENC(zmfwreAfhObIQDyz369dXg==)
    password: ENC(u5djZgMAhFCL4roMXqGn8j3oj6AEcxh0)
    driver-class-name: com.mysql.cj.jdbc.Driver

s3:
  bucket:
    name: ENC(kSZb9yw2JDAVxz/12V7CRNzRskzFvwgqKzJdZzg2nWdIHAnbxBvfknN0fEBTL1j3C6t4LC1iqXk=)
  iam:
    access-key: ENC(1G8ZGZQKMoihcCiT2kgRMLqmKHWfk10LtbhDURaLzDs=)
    secret-key: ENC(iVBb5DDSSAGVQhCL6/KnOPKWC3x89s+9s9SyvR+7/55uBtkdhmL0aobUoL1uGa+67NYXjP1KRUI=)
    region: ENC(906H8BMOAumiA+H0nevzxJUoUGzBG2Nh)
