s3:
  bucket: space-club-image-bucket

  iam:
    access-key: ENC(1G8ZGZQKMoihcCiT2kgRMLqmKHWfk10LtbhDURaLzDs=)
    secret-key: ENC(iVBb5DDSSAGVQhCL6/KnOPKWC3x89s+9s9SyvR+7/55uBtkdhmL0aobUoL1uGa+67NYXjP1KRUI=)
    region: ENC(906H8BMOAumiA+H0nevzxJUoUGzBG2Nh)

  url: https://space-club-image-bucket.s3.ap-northeast-2.amazonaws.com/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
