s3:
  folder:
      name:
          event-poster: space-club-image-bucket/event-poster
          club-logo: space-club-image-bucket/club-logo
          club-cover: space-club-image-bucket/club-cover
          user-profile-image: space-club-image-bucket/user-profile-image
  iam:
    access-key: ENC(1G8ZGZQKMoihcCiT2kgRMLqmKHWfk10LtbhDURaLzDs=)
    secret-key: ENC(iVBb5DDSSAGVQhCL6/KnOPKWC3x89s+9s9SyvR+7/55uBtkdhmL0aobUoL1uGa+67NYXjP1KRUI=)
    region: ENC(906H8BMOAumiA+H0nevzxJUoUGzBG2Nh)
