spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/space-club/local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

s3:
  bucket:
    name: ENC(kSZb9yw2JDAVxz/12V7CRNzRskzFvwgqKzJdZzg2nWdIHAnbxBvfknN0fEBTL1j3C6t4LC1iqXk=)
    club-name: ENC(7kgYNjvsaM9w7JZQJVYrbRoONOnCoLQfqdnA0zxnZLwVpMXElZrfBEY4LcntBZRG)
  iam:
    access-key: ENC(1G8ZGZQKMoihcCiT2kgRMLqmKHWfk10LtbhDURaLzDs=)
    secret-key: ENC(iVBb5DDSSAGVQhCL6/KnOPKWC3x89s+9s9SyvR+7/55uBtkdhmL0aobUoL1uGa+67NYXjP1KRUI=)
    region: ENC(906H8BMOAumiA+H0nevzxJUoUGzBG2Nh)
