
oauth:
  kakao:
    access:
      client-id: ENC(1HPXzg0UKdo61X7AAZeCMZXT1/gU0rhRhDPO3XucG+9yI3uAxIewoZT/E1ybGvsT)
      redirect-url: http://localhost:5173/oauths/kakao/callback
      client-secret: ENC(azg1Eb4DTVE7mvByLggSse6ZZGAseZKavbcdVHmux7Oob1fnk2+VlVvwdJB61VcJ)

jwt:
  header: access-token
  issuer: space-club
  client-secret: ENC(2qr8v6d7x0P13dZVjQx4XToeeUHUh7tW)
  expiry-seconds: 30000 # 임시 값
