spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/space-club
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        format_sql: true
        highlight_sql: true
        create_empty_composites:
          enabled: true
    defer-datasource-initialization: true
